# Generated by Django 2.2.7 on 2019-11-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityScheduleDetails',
            new_name='ActivitySchedule',
        ),
    ]
