# Generated by Django 2.2.7 on 2019-11-26 08:29

import api.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191125_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recurring',
            field=models.BooleanField(default=False, verbose_name='Is the Activity repeating'),
        ),
        migrations.AddField(
            model_name='activity',
            name='repetition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', verbose_name='Details of repetition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='priority',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Priority of the event [0..100]'),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='privacy',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.ActivitySchedule.default_privacy, verbose_name='Privacy Settings'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Group Description'),
        ),
    ]
