# Generated by Django 2.2.7 on 2019-11-26 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191126_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(verbose_name='Duration of each start end pair'), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Time zone of the User'),
        ),
    ]
