# Generated by Django 2.2.7 on 2019-11-27 17:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191126_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(verbose_name='Duration of each start end pair'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='repetition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Details of repetition'),
        ),
    ]
