# Generated by Django 2.2.7 on 2019-11-27 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191127_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='durations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(verbose_name='Duration of each start end pair'), blank=True, null=True, size=None),
        ),
    ]
