# Generated by Django 2.2.7 on 2019-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191127_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='schedules', through='api.ActivitySchedule', to='api.Activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activityschedule',
            unique_together={('activity', 'schedule')},
        ),
    ]
