# Generated by Django 2.2.7 on 2019-11-29 08:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191128_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='OGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Group Description')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Circular Profile Pic for group')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background cover pic for group')),
            ],
        ),
        migrations.CreateModel(
            name='OGroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.OGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='activities',
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(verbose_name='Ending DateTime for the activity'), size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(verbose_name='Starting DateTime for the activity'), size=None),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.Schedule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.Schedule'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='ogroupmembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ogroup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.Schedule'),
        ),
    ]
