# Generated by Django 2.2.7 on 2019-12-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191201_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='api.Schedule'),
        ),
    ]
