# Generated by Django 2.2.7 on 2019-12-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191201_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogroup',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
    ]
