# Generated by Django 2.2.7 on 2020-04-12 21:10

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191201_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='permission',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.Schedule.defaultPermission, verbose_name='Permission details of a Schedule'),
        ),
    ]
