# Generated by Django 2.2.7 on 2020-04-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_schedule_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='permission',
        ),
    ]
