# Generated by Django 2.2.7 on 2020-04-12 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_schedule_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, verbose_name='Weekdays of the event'), default=['Monday'], size=None),
            preserve_default=False,
        ),
    ]
