# Generated by Django 3.0.5 on 2020-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_activity_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceToken',
            field=models.CharField(blank=True, default='None', max_length=600, verbose_name='Mobile Device Id'),
        ),
    ]
