# Generated by Django 3.0.5 on 2020-04-29 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True, verbose_name='Weekdays of the event'), size=None),
        ),
    ]
