# Generated by Django 3.0.6 on 2020-05-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_contacts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('requester', 'reciever')},
        ),
    ]
