# Generated by Django 3.0.6 on 2020-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200511_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='state',
            field=models.CharField(choices=[('req', 'Requested'), ('acc', 'Accepted')], db_index=True, max_length=4, verbose_name='State of connection'),
        ),
    ]
