# Generated by Django 3.0.6 on 2020-05-11 13:48

import api.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200511_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogroup',
            name='members',
            field=models.ManyToManyField(through='api.OGroupMembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ogroupmembers',
            name='priveledges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.models.OGroupMembers.defaultPrivaledges, verbose_name="User's priveledges in the group"),
        ),
        migrations.AlterField(
            model_name='ogroupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembers', to='api.OGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='ogroupmembers',
            unique_together={('group', 'member')},
        ),
    ]
