# Generated by Django 3.0.6 on 2020-05-12 01:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_ogroupmembers_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, verbose_name='Weekdays of the event'), blank=True, null=True, size=None),
        ),
    ]
