# Generated by Django 3.0.6 on 2020-05-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='member_users',
        ),
    ]
