# Generated by Django 3.0.6 on 2020-05-14 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_room_member_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='member_users',
            field=models.ManyToManyField(related_name='rooms', through='chat.RoomMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
